# Generated by Django 3.0.5 on 2020-04-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mdPoll',
            new_name='Pollmd',
        ),
    ]
