# Generated by Django 3.0.5 on 2020-04-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0002_auto_20200409_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmd',
            name='bostion',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
